// EN QUESTION BANK - single source for site pages AND daily EN Shorts.
// Every entry verified against the official source shown in kaynak_url.

var SORULAR_EN = [
  {"id": 1, "kategori": "social-security", "soru": "Social Security checks rise 2.8% in 2026 — here's what that means",
   "cevap_soz": "The 2026 cost of living adjustment is 2.8 percent. The average retired worker's check goes up about 56 dollars, from roughly 2,015 to 2,071 dollars a month. Note: the raise applies to your gross benefit — Medicare premium changes can make your net deposit differ.",
   "satirlar": ["2026 COLA: +2.8%", "Average retiree: +$56/month", "Applies to GROSS benefit", "Medicare premiums affect net"],
   "kaynak": "ssa.gov", "kaynak_url": "https://www.ssa.gov/cola/"},
  {"id": 2, "kategori": "social-security", "soru": "Claiming Social Security at 62 cuts your check up to 30% — forever",
   "cevap_soz": "You can claim retirement benefits as early as 62, but if your full retirement age is 67, claiming at 62 permanently reduces your monthly check by up to 30 percent. The reduction does not go away when you reach full retirement age.",
   "satirlar": ["Earliest claim: age 62", "Cut: up to 30% if FRA is 67", "The reduction is PERMANENT"],
   "kaynak": "ssa.gov", "kaynak_url": "https://www.ssa.gov/benefits/retirement/planner/agereduction.html"},
  {"id": 3, "kategori": "social-security", "soru": "Waiting past full retirement age grows your Social Security 8% a year",
   "cevap_soz": "For every year you delay claiming past your full retirement age, your benefit grows by 8 percent, up until age 70. Waiting from 67 to 70 means a check about 24 percent bigger — for life. After 70 there is no extra credit, so there's no reason to wait longer.",
   "satirlar": ["Delayed credit: +8% per year", "67 → 70 = about +24%", "No extra growth after 70"],
   "kaynak": "ssa.gov", "kaynak_url": "https://www.ssa.gov/benefits/retirement/planner/delayret.html"},
  {"id": 4, "kategori": "social-security", "soru": "Working while on Social Security? The 2026 earnings limit is $24,480",
   "cevap_soz": "If you collect benefits before full retirement age and keep working, 1 dollar is withheld for every 2 dollars you earn above 24,480 dollars in 2026. In the year you reach full retirement age the limit jumps to 65,160. From that month on, there is no limit at all.",
   "satirlar": ["Under FRA: limit $24,480", "$1 withheld per $2 over", "FRA year: $65,160 ($1 per $3)", "After FRA: NO limit"],
   "kaynak": "ssa.gov", "kaynak_url": "https://www.ssa.gov/benefits/retirement/planner/whileworking.html"},
  {"id": 5, "kategori": "paycheck", "soru": "You stop paying Social Security tax above $184,500 in 2026",
   "cevap_soz": "Social Security tax is 6.2 percent of your wages, but only up to the wage base — 184,500 dollars in 2026, up from 176,100 in 2025. Earn more than that and the 6.2 percent deduction stops for the rest of the year. Medicare tax, however, has no cap.",
   "satirlar": ["2026 wage base: $184,500", "Tax: 6.2% up to the cap", "Max SS tax: $11,439", "Medicare has NO cap"],
   "kaynak": "ssa.gov", "kaynak_url": "https://www.ssa.gov/news/en/cola/"},
  {"id": 6, "kategori": "paycheck", "soru": "Federal minimum wage is still $7.25 — but your state may owe you more",
   "cevap_soz": "The federal minimum wage has been 7 dollars 25 cents since 2009. But most states set a higher minimum, and when state and federal law differ, you're entitled to the HIGHER rate. Check your state's rate — it may have changed on January first.",
   "satirlar": ["Federal: $7.25 (since 2009)", "Most states set HIGHER rates", "You get whichever is higher"],
   "kaynak": "dol.gov", "kaynak_url": "https://www.dol.gov/agencies/whd/minimum-wage/state"},
  {"id": 7, "kategori": "paycheck", "soru": "Tipped workers: if tips don't reach $7.25/hour, your boss pays the gap",
   "cevap_soz": "Federal law lets employers pay tipped workers a base of just 2 dollars 13 cents an hour. But base pay plus tips must equal at least the full minimum wage of 7 25. If your tips don't get you there, your employer is legally required to make up the difference.",
   "satirlar": ["Tipped base: $2.13/hour", "Base + tips must reach $7.25", "Short? Employer pays the gap"],
   "kaynak": "dol.gov", "kaynak_url": "https://www.dol.gov/agencies/whd/tips"},
  {"id": 8, "kategori": "paycheck", "soru": "Overtime: over 40 hours a week means time-and-a-half — for most workers",
   "cevap_soz": "Under the Fair Labor Standards Act, non-exempt employees must get 1.5 times their regular rate for every hour over 40 in a workweek. There's no federal limit on how many hours an adult can be required to work — but every overtime hour must be paid at the higher rate.",
   "satirlar": ["Over 40 hrs/week = 1.5× pay", "Applies to non-exempt employees", "Unpaid overtime = wage theft"],
   "kaynak": "dol.gov", "kaynak_url": "https://www.dol.gov/agencies/whd/overtime"},
  {"id": 9, "kategori": "paycheck", "soru": "Your manager keeping your tips? That's illegal under federal law",
   "cevap_soz": "Tips belong to workers. Federal law says employers, managers and supervisors may not keep any portion of employees' tips, no matter what. Tip pooling among coworkers can be legal — a manager taking a cut is not.",
   "satirlar": ["Tips belong to WORKERS", "Managers may not take a cut", "Tip pools: only between staff"],
   "kaynak": "dol.gov", "kaynak_url": "https://www.dol.gov/agencies/whd/tips"},
  {"id": 10, "kategori": "paycheck", "soru": "Yes, you're allowed to discuss your salary with coworkers",
   "cevap_soz": "Many employers say salaries are confidential. But under the National Labor Relations Act, most private-sector employees have the right to discuss wages with coworkers, and policies that ban it are unlawful. Pay secrecy protects low pay — the law protects you.",
   "satirlar": ["Discussing pay = protected right", "Salary-secrecy bans: unlawful", "Private-sector employees (NLRA)"],
   "kaynak": "nlrb.gov", "kaynak_url": "https://www.nlrb.gov/about-nlrb/rights-we-protect/your-rights/your-rights-to-discuss-wages"},
  {"id": 11, "kategori": "leave", "soru": "FMLA: 12 weeks of job-protected leave — do you qualify?",
   "cevap_soz": "The Family and Medical Leave Act gives up to 12 weeks of unpaid, job-protected leave per year for serious health conditions, a new child, or caring for close family. To qualify: 12 months with your employer, 1,250 hours worked, and a company with 50 plus employees within 75 miles.",
   "satirlar": ["Up to 12 weeks, job protected", "Need: 12 months + 1,250 hours", "Employer: 50+ employees", "Unpaid under federal law"],
   "kaynak": "dol.gov", "kaynak_url": "https://www.dol.gov/agencies/whd/fmla"},
  {"id": 12, "kategori": "leave", "soru": "FMLA is unpaid — but your state might pay you for family leave",
   "cevap_soz": "Federal FMLA protects your job but pays nothing. A growing number of states run PAID family and medical leave programs that replace part of your wages during leave. If you're planning for a baby or surgery, check your state's program before assuming you get nothing.",
   "satirlar": ["Federal FMLA: unpaid", "Several states: PAID leave programs", "Check your state before leave"],
   "kaynak": "dol.gov", "kaynak_url": "https://www.dol.gov/agencies/whd/fmla"},
  {"id": 13, "kategori": "paycheck", "soru": "At-will employment: they can fire you for no reason — not for an illegal one",
   "cevap_soz": "In most states, employment is at-will: you can be let go without cause. But no employer may fire you for illegal reasons — your race, sex, religion, age over 40, disability, pregnancy, or for reporting violations. That's discrimination or retaliation, and it's actionable.",
   "satirlar": ["At-will: no cause needed", "BUT illegal reasons are barred", "Discrimination, retaliation = actionable"],
   "kaynak": "eeoc.gov", "kaynak_url": "https://www.eeoc.gov/prohibited-employment-policiespractices"},
  {"id": 14, "kategori": "paycheck", "soru": "Quit or fired: how fast must your final paycheck arrive?",
   "cevap_soz": "Federal law sets no deadline for your final paycheck — your STATE law does, and some states require payment immediately or on your last day, especially if you were let go. Don't let an employer tell you 'next payroll cycle' before checking your state's rule.",
   "satirlar": ["Deadline set by STATE law", "Some states: same-day payment", "Check before accepting delays"],
   "kaynak": "dol.gov", "kaynak_url": "https://www.dol.gov/general/topic/wages/lastpaycheck"},
  {"id": 15, "kategori": "credit", "soru": "Wrong charge on your credit card? You have 60 days to dispute it",
   "cevap_soz": "Under the Fair Credit Billing Act you can dispute billing errors — wrong amounts, charges you never made, goods never delivered — by writing to your card issuer within 60 days of the statement. They must investigate, and you don't have to pay the disputed amount meanwhile.",
   "satirlar": ["60 days to dispute in writing", "Issuer MUST investigate", "Disputed amount: on hold"],
   "kaynak": "consumerfinance.gov", "kaynak_url": "https://www.consumerfinance.gov/ask-cfpb/how-do-i-dispute-a-charge-on-my-credit-card-bill-en-61/"},
  {"id": 16, "kategori": "debt", "soru": "Debt collectors can't call you before 8am or after 9pm",
   "cevap_soz": "The Fair Debt Collection Practices Act bans collectors from calling before 8 a.m. or after 9 p.m., harassing you, using obscene language, or threatening things they can't legally do. You can also tell them in writing to stop contacting you — and they generally must.",
   "satirlar": ["No calls before 8am / after 9pm", "Harassment & threats: illegal", "Written stop request works"],
   "kaynak": "consumerfinance.gov", "kaynak_url": "https://www.consumerfinance.gov/consumer-tools/debt-collection/"},
  {"id": 17, "kategori": "debt", "soru": "Never pay a debt collector before demanding validation",
   "cevap_soz": "Collectors must send you a validation notice with the debt amount, the creditor's name, and your rights. If you dispute the debt in writing within 30 days, collection must pause until they verify it. Scam collectors count on you not knowing this.",
   "satirlar": ["Validation notice: required", "30 days to dispute in writing", "Collection pauses until verified"],
   "kaynak": "consumerfinance.gov", "kaynak_url": "https://www.consumerfinance.gov/consumer-tools/debt-collection/"},
  {"id": 18, "kategori": "credit", "soru": "Your credit reports are free every week — from one official site only",
   "cevap_soz": "You're entitled to free credit reports from all three bureaus — Equifax, Experian and TransUnion — every week, at AnnualCreditReport.com. That's the only federally authorized site. Anyone else charging you for your own report is selling you something you already own.",
   "satirlar": ["Free reports WEEKLY", "All 3 bureaus", "Only: AnnualCreditReport.com"],
   "kaynak": "consumerfinance.gov", "kaynak_url": "https://www.consumerfinance.gov/ask-cfpb/how-do-i-get-a-free-copy-of-my-credit-reports-en-5/"},
  {"id": 19, "kategori": "consumer", "soru": "Door-to-door purchase? You get 3 days to cancel — by law",
   "cevap_soz": "The FTC's Cooling-Off Rule gives you 3 business days to cancel purchases of 25 dollars or more made at your home, or 130 dollars or more at temporary locations like hotel ballrooms. The seller must tell you about this right and give you a cancellation form.",
   "satirlar": ["3 business days to cancel", "$25+ at your home", "Seller MUST inform you"],
   "kaynak": "ftc.gov", "kaynak_url": "https://consumer.ftc.gov/articles/buyers-remorse-when-ftcs-cooling-rule-may-help"},
  {"id": 20, "kategori": "social-security", "soru": "Miss your Medicare window at 65 and you pay a penalty for life",
   "cevap_soz": "Your initial Medicare enrollment window is 7 months around your 65th birthday. Skip Part B without other qualifying coverage and your premium goes up about 10 percent for every 12 months you delayed — and that penalty lasts as long as you have Part B.",
   "satirlar": ["Window: 7 months around 65", "Late Part B: ~10% per year missed", "Penalty is usually LIFELONG"],
   "kaynak": "medicare.gov", "kaynak_url": "https://www.medicare.gov/basics/costs/medicare-costs/avoid-penalties"}
];

if (typeof module !== "undefined" && module.exports) module.exports = SORULAR_EN;
