// ============================================================
// SORU BANKASI — günlük Short + site SSS için TEK kaynak.
// Her giriş kanun dayanağıyla doğrulanmıştır; haber/derleme DEĞİL,
// yerleşik mevzuat bilgisidir. Yeni parti eklerken aynı disiplin:
// dayanaksız soru girilmez, emin olunmayan rakam yazılmaz.
// ============================================================

var SORULAR = [
  { id: 1, kategori: "kıdem", soru: "İstifa eden işçi kıdem tazminatı alabilir mi?",
    cevap_soz: "Kural olarak hayır. Ama istisnalar var: haklı nedenle fesih, erkek işçinin askere gitmesi, kadın işçinin evlilikten sonraki bir yıl içinde ayrılması ve emeklilik ya da yaş dışındaki emeklilik şartlarını tamamlayarak ayrılma. Bu hallerde istifa etseniz bile tazminat hakkı doğar.",
    satirlar: ["Kural: istifada tazminat YOK", "İstisna: haklı neden, askerlik", "İstisna: evlilik (kadın, 1 yıl içinde)", "İstisna: emeklilik şartları"],
    dayanak: "1475 sayılı İş Kanunu m.14" },
  { id: 2, kategori: "kıdem", soru: "Kıdem tazminatı için en az kaç yıl çalışmak gerekir?",
    cevap_soz: "Aynı işverende en az bir tam yıl. Bir yılı doldurmadan işten ayrılırsanız veya çıkarılırsanız kıdem tazminatı doğmaz. Bir yılın üzerindeki her tam yıl için bir aylık giydirilmiş brüt ücret, artan aylar için de oranlı ödeme yapılır.",
    satirlar: ["En az 1 TAM yıl şart", "Her tam yıl = 1 aylık brüt ücret", "Artan aylar oranlanır"],
    dayanak: "1475 sayılı İş Kanunu m.14" },
  { id: 3, kategori: "kıdem", soru: "Kıdem tazminatından vergi kesilir mi?",
    cevap_soz: "Gelir vergisi kesilmez. Yasal tavana kadar olan kıdem tazminatından yalnızca binde yedi virgül elli dokuz oranında damga vergisi kesilir. Yani yüz bin liralık brüt kıdem tazminatından eline yaklaşık doksan dokuz bin iki yüz kırk lira geçer.",
    satirlar: ["Gelir vergisi: YOK", "Sadece damga vergisi: binde 7,59", "100.000 TL brüt → ~99.241 TL net"],
    dayanak: "1475 s.K. m.14; GVK m.25" },
  { id: 4, kategori: "ihbar", soru: "İhbar süresi kaç hafta? İşten çıkarılmadan önce ne kadar önce haber verilmeli?",
    cevap_soz: "Kıdeme göre değişir: altı aydan az çalışana iki hafta, altı ay ile bir buçuk yıl arası dört hafta, bir buçuk ile üç yıl arası altı hafta, üç yıldan fazla çalışana sekiz hafta önceden bildirim yapılmalı. Bildirim yapılmazsa bu sürenin ücreti ihbar tazminatı olarak ödenir.",
    satirlar: ["6 aydan az: 2 hafta", "6 ay – 1,5 yıl: 4 hafta", "1,5 – 3 yıl: 6 hafta", "3 yıldan fazla: 8 hafta"],
    dayanak: "4857 sayılı İş Kanunu m.17" },
  { id: 5, kategori: "ihbar", soru: "İhbar süresinde iş arama izniniz olduğunu biliyor muydunuz?",
    cevap_soz: "İhbar süresi boyunca işveren, iş saatleri içinde günde en az iki saat ücretli iş arama izni vermek zorunda. İşçi isterse bu saatleri birleştirip toplu da kullanabilir. Bu izin kullandırılmazsa o sürenin ücreti zamlı ödenir.",
    satirlar: ["Günde en az 2 saat ÜCRETLİ izin", "Birleştirip toplu kullanılabilir", "Kullandırılmazsa: zamlı ücret"],
    dayanak: "4857 sayılı İş Kanunu m.27" },
  { id: 6, kategori: "deneme", soru: "Deneme süresi en fazla ne kadar olabilir?",
    cevap_soz: "En fazla iki ay. Yalnızca toplu iş sözleşmesiyle dört aya kadar uzatılabilir. Sözleşmenize daha uzun deneme süresi yazılmışsa geçersizdir. Deneme süresinde de çalıştığınız her günün ücreti ve sigortası eksiksiz ödenmek zorundadır.",
    satirlar: ["En fazla 2 ay", "Toplu sözleşmeyle en fazla 4 ay", "Ücret ve SGK ilk günden zorunlu"],
    dayanak: "4857 sayılı İş Kanunu m.15" },
  { id: 7, kategori: "maaş", soru: "Maaşınız 20 gün geciktiyse çalışmayı bırakma hakkınız var",
    cevap_soz: "Ücreti ödeme gününden itibaren yirmi gün içinde mücbir sebep dışında ödenmeyen işçi, iş görme borcunu yerine getirmekten kaçınabilir. Bu, grev sayılmaz. Ayrıca ücreti ödenmeyen işçi iş sözleşmesini haklı nedenle feshedip kıdem tazminatını da alabilir.",
    satirlar: ["20 gün gecikme → çalışmama hakkı", "Bu grev SAYILMAZ", "Haklı fesih + kıdem hakkı doğar"],
    dayanak: "4857 s.K. m.34 ve m.24/II-e" },
  { id: 8, kategori: "fazla-mesai", soru: "Fazla mesai ücreti nasıl hesaplanır?",
    cevap_soz: "Haftalık kırk beş saati aşan her saat fazla çalışmadır ve normal saat ücretinizin yüzde elli fazlasıyla ödenir. Örnek: saat ücretiniz yüz lira ise fazla mesainin saati yüz elli liradır. İsterseniz ücret yerine her fazla saat için bir buçuk saat serbest zaman da talep edebilirsiniz.",
    satirlar: ["45 saat/hafta üstü = fazla mesai", "Saat ücreti × 1,5", "Alternatif: saat başına 1,5 saat izin"],
    dayanak: "4857 sayılı İş Kanunu m.41" },
  { id: 9, kategori: "fazla-mesai", soru: "Yılda en fazla kaç saat fazla mesai yaptırılabilir?",
    cevap_soz: "Yılda en fazla iki yüz yetmiş saat. Bu sınırın üzerinde fazla çalışma yaptırılamaz. Ayrıca fazla mesai için işçinin onayı gerekir; onay vermeyen işçi fazla mesaiye zorlanamaz.",
    satirlar: ["Yıllık sınır: 270 saat", "İşçinin ONAYI şart", "Onay vermeyen zorlanamaz"],
    dayanak: "4857 s.K. m.41; FÇY m.8-9" },
  { id: 10, kategori: "izin", soru: "Yıllık izniniz kaç gün? Çoğu kişi yanlış biliyor",
    cevap_soz: "Bir ile beş yıl arası çalışana on dört gün, beş yıldan fazla on beş yıldan az çalışana yirmi gün, on beş yıl ve üzerine yirmi altı gün. On sekiz yaş ve altı ile elli yaş ve üzeri işçilere süreye bakılmaksızın en az yirmi gün verilir. Bunlar asgari sürelerdir.",
    satirlar: ["1–5 yıl: 14 gün", "5'ten fazla: 20 gün", "15 yıl ve üzeri: 26 gün", "≤18 yaş / ≥50 yaş: en az 20 gün"],
    dayanak: "4857 sayılı İş Kanunu m.53" },
  { id: 11, kategori: "izin", soru: "Kullanılmayan yıllık izinler yanar mı?",
    cevap_soz: "Hayır, yanmaz, birikir. İş sözleşmesi hangi sebeple biterse bitsin, kullanılmamış tüm izinlerin ücreti son brüt ücret üzerinden ödenmek zorundadır. Bu alacak için zamanaşımı, işten ayrıldığınız tarihten itibaren beş yıldır.",
    satirlar: ["İzin YANMAZ, birikir", "Çıkışta ücreti ödenir (son brüt)", "Zamanaşımı: fesihten itibaren 5 yıl"],
    dayanak: "4857 sayılı İş Kanunu m.59" },
  { id: 12, kategori: "izin", soru: "Yıllık izindeyken hafta sonu ve bayramlar izinden düşülür mü?",
    cevap_soz: "Düşülmez. İzin süresine denk gelen hafta tatili, ulusal bayram ve genel tatil günleri izin süresinden sayılmaz. Yani on dört günlük izin kullanan bir işçi, araya giren tatillerle birlikte takvimde fiilen daha uzun süre izinli olur.",
    satirlar: ["Hafta tatili izinden SAYILMAZ", "Bayram ve genel tatiller de sayılmaz", "14 gün izin > 14 takvim günü"],
    dayanak: "4857 sayılı İş Kanunu m.56" },
  { id: 13, kategori: "izin", soru: "Yıllık izinde başka işte çalışmak yasak — ücret geri alınır",
    cevap_soz: "Yıllık iznini kullanan işçi, izin süresinde ücret karşılığı başka bir işte çalışırsa, işveren ödediği izin ücretini geri alabilir. İzin dinlenme hakkıdır ve amacı dışında kullanılamaz.",
    satirlar: ["İzinde başka işte çalışmak yasak", "Tespit edilirse izin ücreti geri alınır"],
    dayanak: "4857 sayılı İş Kanunu m.58" },
  { id: 14, kategori: "izin", soru: "İşveren 'izin veremem' diyebilir mi? İzin bölünebilir mi?",
    cevap_soz: "İzin zamanını belirleme yetkisi işverende olsa da izni tamamen kullandırmamak yasaya aykırıdır; izin hakkından vazgeçilemez. İzin, tarafların anlaşmasıyla bölümler halinde kullanılabilir; ancak bir bölümü on günden az olamaz.",
    satirlar: ["İzin hakkından VAZGEÇİLEMEZ", "Zamanı işveren belirler, yok sayamaz", "Bölünebilir; bir parça ≥ 10 gün"],
    dayanak: "4857 s.K. m.53 ve m.56" },
  { id: 15, kategori: "kira", soru: "Depozito en fazla kaç aylık kira olabilir?",
    cevap_soz: "En fazla üç aylık kira bedeli kadar. Sözleşmeye daha yükseği yazılsa bile üç ayı aşan kısım geçersizdir. Kanuna göre depozitonun vadeli tasarruf hesabına yatırılması gerekir; ev sahibi bankadan bu parayı ancak kiracının rızası veya mahkeme kararıyla çekebilir.",
    satirlar: ["Üst sınır: 3 aylık kira", "Fazlası GEÇERSİZ", "Vadeli hesaba yatırılmalı"],
    dayanak: "TBK m.342" },
  { id: 16, kategori: "kira", soru: "Ev sahibi TÜFE üzerinde kira zammı isteyebilir mi?",
    cevap_soz: "İsteyemez. Konut ve çatılı işyeri kiralarında artış, TÜFE'nin on iki aylık ortalamalara göre değişim oranını geçemez. Sözleşmede daha yüksek oran yazsa bile aşan kısım geçersizdir. Temmuz iki bin yirmi altı için bu sınır yüzde otuz iki virgül sıfır üçtür.",
    satirlar: ["Sınır: TÜFE 12 aylık ortalama", "Sözleşmede fazlası yazsa da geçersiz", "Temmuz 2026: %32,03"],
    dayanak: "TBK m.344" },
  { id: 17, kategori: "kira", soru: "Sözleşme bitti diye kiracı evden çıkarılabilir mi?",
    cevap_soz: "Çıkarılamaz. Konut kirasında sözleşme süresinin dolması tek başına tahliye sebebi değildir; sözleşme kendiliğinden uzar. Ev sahibi ancak kanundaki sebeplerle tahliye isteyebilir: kendisinin veya yakınlarının konut ihtiyacı, esaslı onarım, iki haklı ihtar veya on yıllık uzama süresinin dolması gibi.",
    satirlar: ["Süre doldu ≠ tahliye sebebi", "Geçerli sebep: ihtiyaç, esaslı onarım", "İki haklı ihtar, 10 yıl uzama"],
    dayanak: "TBK m.347 vd." },
  { id: 18, kategori: "kira", soru: "Kira sözleşmesiyle aynı gün imzalatılan tahliye taahhüdü geçersiz",
    cevap_soz: "Tahliye taahhüdü, kiracının belirli bir tarihte evi boşaltmayı yazılı olarak üstlenmesidir. Ancak geçerli olması için kiralananın tesliminden SONRA verilmesi gerekir. Sözleşmeyle aynı anda, baskı altında imzalatılan taahhütler yerleşik içtihatta geçersiz kabul edilir.",
    satirlar: ["Taahhüt teslimden SONRA verilmeli", "Sözleşmeyle aynı gün = geçersiz", "Yazılı olmak zorunda"],
    dayanak: "TBK m.352/1" },
  { id: 19, kategori: "kira", soru: "Aidatı kiracı mı ev sahibi mi öder?",
    cevap_soz: "Kural şu: kullanımdan doğan olağan giderler, yani aidatın temizlik, kapıcı, elektrik, ısınma gibi kalemleri kiracıya; binanın ana yapısına ilişkin demirbaş, büyük onarım ve yenileme giderleri ev sahibine aittir. Sözleşmede aksine düzenleme yapılabilir, kontrol edin.",
    satirlar: ["Olağan kullanım giderleri: KİRACI", "Demirbaş/büyük onarım: EV SAHİBİ", "Sözleşme hükmünü kontrol et"],
    dayanak: "TBK m.341" },
  { id: 20, kategori: "tüketici", soru: "İnternetten aldığınız ürünü 14 gün içinde sebepsiz iade edebilirsiniz",
    cevap_soz: "Mesafeli satışlarda, yani internet veya telefonla yapılan alışverişlerde teslimden itibaren on dört gün içinde hiçbir gerekçe göstermeden ve ceza ödemeden cayma hakkınız var. Satıcı, cayma bildiriminden itibaren on dört gün içinde tüm ödemeyi iade etmek zorunda.",
    satirlar: ["14 gün cayma hakkı", "Gerekçe göstermek GEREKMEZ", "Ödeme 14 günde iade edilir"],
    dayanak: "6502 s.K. m.48; Mesafeli Sözleşmeler Yön." },
  { id: 21, kategori: "tüketici", soru: "Aldığınız ürün bozuk çıktı: 4 seçimlik hakkınız var",
    cevap_soz: "Ayıplı çıkan malda tüketicinin dört seçimlik hakkı vardır: sözleşmeden dönüp parayı geri istemek, ayıp oranında indirim, ücretsiz onarım veya ayıpsız yenisiyle değişim. Seçim tüketicinindir; satıcı 'sadece tamir ederim' diyemez. Bu haklar teslimden itibaren en az iki yıl sürer.",
    satirlar: ["1) Para iadesi  2) İndirim", "3) Ücretsiz onarım  4) Değişim", "Seçim TÜKETİCİNİN", "Süre: en az 2 yıl"],
    dayanak: "6502 s.K. m.11" },
  { id: 22, kategori: "tüketici", soru: "'Aboneliği iptal edemezsin' dayatması geçersiz",
    cevap_soz: "Belirsiz süreli veya bir yıldan uzun süreli abonelik sözleşmelerinde tüketici istediği zaman, gerekçe göstermeden feshedebilir. Fesih talebiniz size ağır yük getiren şartlara bağlanamaz. Satıcı talebi süresi içinde işleme almak zorundadır; sürüncemede bırakmak yasaya aykırıdır.",
    satirlar: ["İstediğin an fesih hakkı", "Gerekçe gerekmez", "Zorlaştırıcı şart geçersiz"],
    dayanak: "6502 s.K. m.52" },
  { id: 23, kategori: "tüketici", soru: "Tüketici hakem heyetine başvuru tamamen ücretsiz",
    cevap_soz: "Satıcıyla çözemediğiniz uyuşmazlıklar için tüketici hakem heyetine başvuru ücretsizdir; avukat da gerekmez. Başvuruyu e-Devlet üzerinden Tüketici Bilgi Sistemi ile dakikalar içinde yapabilirsiniz. Karar bağlayıcıdır; satıcı uymazsa icra yoluna gidilebilir.",
    satirlar: ["Başvuru ÜCRETSİZ, avukatsız", "e-Devlet'ten online yapılır", "Karar bağlayıcı, icra edilebilir"],
    dayanak: "6502 s.K. m.66 vd." },
  { id: 24, kategori: "maaş", soru: "Maaşın elden ödenmesi işçi için neden tehlikeli?",
    cevap_soz: "Elden ve kayıt dışı ödenen maaş; kıdem tazminatınızı, ihbar tazminatınızı, emekli maaşınızı ve işsizlik maaşınızı düşürür, çünkü hepsi kayıtlı brüt ücret üzerinden hesaplanır. Gerçek maaşın bordroya yazılmasını istemek yasal hakkınızdır; fark için hizmet tespit davası da açılabilir.",
    satirlar: ["Elden maaş = düşük kıdem/emeklilik", "Her hak KAYITLI brütten hesaplanır", "Hizmet tespit davası açılabilir"],
    dayanak: "5510 s.K. m.86; 4857 s.K. m.32" }
];

if (typeof module !== "undefined" && module.exports) module.exports = SORULAR;
